name: Fuzzing
on:
  pull_request: {}

permissions: read-all

jobs:
  PR:
    runs-on: [self-hosted, linux]
    container:
      image: gcr.io/oss-fuzz-base/base-builder-python
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
       sanitizer:
          - undefined
    steps:
    - name: Checkout submodules
      uses: actions/checkout@v3
      id: checkout
      with:
        path: storage/proxy-model.py
        submodules: true

    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@50707aeae5d98426f417414b7854fdf47bc4def6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sanitizer: ${{ matrix.sanitizer }}
        language: python
        upload-build: true
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@50707aeae5d98426f417414b7854fdf47bc4def6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 600
        mode: 'code-change'
        sanitizer: ${{ matrix.sanitizer }}