name: Fuzzing
on:
  pull_request: {}

permissions: read-all

env:
  SOLANA_URL: http://10.4.0.2:8899

jobs:
  build_docker_image:
    runs-on: [self-hosted, linux]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            SOLANA_URL=${{ env.SOLANA_URL }}
          file: .clusterfuzzlite/run_fuzzers/Dockerfile
          push: true
          tags: neonlabsorg/fuzzing:latest
  PR:
    needs: build_docker_image
    runs-on: [self-hosted, linux]
    env:
      LOG_CFG: log_cfg_fuzzing.json
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      POSTGRES_HOST: 10.4.0.3
      PP_SOLANA_URL: https://api.devnet.solana.com
      PYTH_MAPPING_ACCOUNT: BmA9Z6FjioHJPpjT39QazZyhDRUdZy2ezwx4GiDdE2u2
    container:
      image: gcr.io/oss-fuzz-base/base-builder-python
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
       sanitizer:
          - undefined
    steps:
    - name: Checkout submodules
      uses: actions/checkout@v3
      id: checkout
      with:
        ref: ${{ github.ref }}
        path: storage/proxy-model.py
        submodules: true

    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@50707aeae5d98426f417414b7854fdf47bc4def6
      with:
        bad-build-check: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sanitizer: ${{ matrix.sanitizer }}
        language: python
        upload-build: false
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      id: run
      uses: neonlabsorg/clusterfuzzlite/actions/run_fuzzers@b05601b4377041cc4b3f6122a2411612d5dadc79
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 300
        mode: 'code-change'
        sanitizer: ${{ matrix.sanitizer }}
        language: python
    - name: Clean up
      if: always()
      run: rm -rf ${{ github.workspace }}
