name: Build proxy docker image
on:
  workflow_dispatch:
    inputs:
      full_test_suite:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: TEST
        run: echo ${{ github.event.inputs.full_test_suite }}
